### PR TITLE
Fix csn + Frontpage links

### PR DESCRIPTION
**Pull request by jaakoob**
Fix the links on the frontpage in the news section (capitalization) and update infos regarding the csn. 

How shall images/ logos be uploaded?

### CODE REVIEW

**Comment by v0tti** [comment]
Thanks. Logos for meetings and networks can be uploaded directly in their corresponding directories. If it is the main logo for the network/meeting it should be named like the corresponding article.

**Comment by v0tti** [comment]
Other images can also be uploaded to the same directory as its parent article. Maybe we should add a convention to prefix the filenames with the filename of the network/meeting page?

**Comment by clerie** [comment]
> Maybe we should add a convention to prefix the filenames with the filename of the network/meeting page?

That sounds like a good idea. But I wouldn't specify more details and see how the requirements develop future.

**Comment by v0tti** [comment]
I am gonna merge this for the broken frontpage links. If you want to upload images feel free to do so in another PR.

**Pull request merged**
